name = "cloudflare-next-images"
main = "./dist/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[observability]
enabled = true

[[routes]]
pattern = "ristill.club/_next/*"
zone_name = "ristill.club"

[build]
command = "pnpm run build"
watch_dir = "src"


